### ISSUE TITLE
How do you guys determine the weight when you do ensemble?

### ISSUE THREAD

**Issue by ajing** [dongyp13/Targeted-Adversarial-Attack#1]
Do you have any assumptions about the model population?

**Comment by dongyp13** [comment]
This code is submitted for NIPS2017 Targeted Adversarial Attack competition. We notice that a lot of defense submissions are baseline inception_v3 and ens_adv_inception_resnet_v2 models, so we put a higher weight for them. You can adjust the weights for your purpose.
