### ISSUE TITLE
White-box strategy?

### ISSUE THREAD

**Issue by tiddler** [dongyp13/Targeted-Adversarial-Attack#2]
Please correct me if I am wrong.
In this work, you focus on white-box targeted attack. By applying I-FGSA with Momentum method across different models, you can thereby attack an unknown classifier with the ensembled result. Does it mean that there is actually a transferability in white-box attack?

**Comment by dongyp13** [comment]
Actually, we do not obtain transferability in targeted attacks with the size of perturbation epsilon=16. Momentum method helps to improve white-box attacks than I-FGSM with few iterations.

For non-targeted attacks, we found that momentum method greatly improve the transferability. (Please find the non-targeted attacks in [https://github.com/dongyp13/Non-Targeted-Adversarial-Attacks](https://github.com/dongyp13/Non-Targeted-Adversarial-Attacks).)

**Comment by tiddler** [comment]
Thank you for the response.
BTW, congratulation for the nice work.
